CREATE TABLE IF NOT EXISTS events (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    details VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL ,
    maximum_attendees INTEGER NOT NULL
);